workflows:
  build_study_planner:
    name: Build APK
    environment:
      flutter: stable
    scripts:
      - echo "📦 Running flutter pub get..."
      - flutter pub get
      - echo "✅ pub get finished. Running build..."
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
