workflows:
  build_study_planner:
    name: Build APK
    environment:
      flutter: stable
    scripts:
      - cd app && flutter pub get && flutter build apk --release
    artifacts:
      - app/build/app/outputs/flutter-apk/app-release.apk
